let dados = [
    {
    titulo: "Breaking bad",
    descricao: "Breaking Bad é uma série de televisão americana que acompanha a transformação de Walter White, um professor de química do ensino médio com câncer, em um poderoso chefão do tráfico de   metanfetamina. A série explora a dualidade da natureza humana, mostrando como a necessidade de proteger a família e a luta pela sobrevivência podem levar um homem comum a cometer atos cada vez mais perigosos e imorais. Com uma narrativa envolvente, personagens complexos e uma fotografia impecável, Breaking Bad se tornou um fenômeno cultural e um dos maiores sucessos da televisão, conquistando diversos prêmios e o reconhecimento da crítica especializada.",
    link: "https://pt.wikipedia.org/wiki/Breaking_Bad", 
    tags: "drama walter jesse", 
},
{
    titulo: "Game of Thrones",
    descricao: "Game of Thrones é uma série de fantasia épica baseada na série de livros 'As Crônicas de Gelo e Fogo', de George R. R. Martin. A história se passa em um mundo medieval fictício, onde famílias nobres lutam pelo controle do Trono de Ferro e enfrentam ameaças de criaturas místicas e forças sobrenaturais. A série é conhecida por seus personagens complexos, reviravoltas inesperadas e cenas de batalhas épicas.",
    link: "https://pt.wikipedia.org/wiki/Game_of_Thrones",
    tags: "stark trono guerra",
},
{
    titulo: "Stranger Things",
    descricao: "Stranger Things é uma série de ficção científica ambientada nos anos 80. A trama gira em torno do desaparecimento de um garoto em uma pequena cidade americana e das consequências de experimentos secretos que abrem um portal para uma dimensão alternativa habitada por criaturas monstruosas. A série é uma homenagem aos clássicos do cinema e da televisão, como 'E.T. o Extraterrestre' e 'Stranger Things', e combina elementos de terror, suspense e drama.",
    link: "https://pt.wikipedia.org/wiki/Stranger_Things",
    tags: "misterio suspense crianças",
},
{
    titulo: "The Mandalorian",
    descricao: "The Mandalorian é uma série de televisão de ficção científica ambientada no universo de Star Wars. A trama acompanha um solitário caçador de recompensas mandaloriano que se torna guardião de uma criança da mesma espécie de Yoda.",
    link: "https://pt.wikipedia.org/wiki/The_Mandalorian",
    tags: "starwars mandalorian yoda",
},
{
    titulo: "Black Mirror",
    descricao: "Black Mirror é uma antologia britânica de ficção científica que explora as consequências da tecnologia em nossa sociedade. Cada episódio apresenta uma história independente, geralmente com um final perturbador, que nos faz refletir sobre o futuro da humanidade.",
    link: "https://pt.wikipedia.org/wiki/Black_Mirror",
    tags: "tecnologia futuro distopia",
},
{
    titulo: "Squid Game",
    descricao: "Squid Game é uma série de televisão sul-coreana que se tornou um fenômeno global. A trama gira em torno de um grupo de pessoas endividadas que são convidadas a participar de uma série de jogos mortais com o objetivo de ganhar um prêmio em dinheiro.",
    link: "https://pt.wikipedia.org/wiki/Squid_Game",
    tags: "sobrevivencia jogos mortais coreia"
},
{
    titulo: "Euphoria",
    descricao: "Euphoria é uma série dramática adolescente que explora temas como drogas, sexo, identidade e as dificuldades da vida moderna. A série acompanha um grupo de estudantes do ensino médio em uma pequena cidade americana e suas lutas internas.",
    link: "https://pt.wikipedia.org/wiki/Euphoria_(série_de_televisão)",
    tags: "adolescencia drama drogas",
},
{
    titulo: "Ted Lasso",
    descricao: "Ted Lasso é uma comédia dramática que acompanha um treinador americano de futebol americano, sem experiência no esporte, que é contratado para treinar um time de futebol inglês. A série explora temas como liderança, amizade e superação.",
    link: "https://pt.wikipedia.org/wiki/Ted_Lasso",
    tags: "comedia esporte amizade",
},
{
    titulo: "The Last of Us",
    descricao: "The Last of Us é uma série de drama pós-apocalíptico adaptada do jogo de mesmo nome. A trama se passa em um mundo devastado por um fungo que transforma os humanos em criaturas violentas. Um contrabandista e uma adolescente imune ao fungo embarcam em uma jornada perigosa pelos Estados Unidos.",
    link: "https://pt.wikipedia.org/wiki/The_Last_of_Us_(série_de_televisão)",
    tags: "apocalipse survival horror"
},
{
    titulo: "House of the Dragon",
    descricao: "House of the Dragon é um prelúdio de Game of Thrones que explora a história da Casa Targaryen e os eventos que levaram à Dança dos Dragões, uma guerra civil que quase destruiu a dinastia.",
    link: "https://pt.wikipedia.org/wiki/House_of_the_Dragon",
    tags: "gameofthrones targaryen dragões",
},
{
    titulo: "Severance",
    descricao: "Severance é uma série de ficção científica que explora o conceito de separação da vida profissional da pessoal. Os funcionários de uma empresa de tecnologia têm suas memórias do trabalho completamente separadas de suas vidas pessoais.",
    link: "https://pt.wikipedia.org/wiki/Severance_(série_de_televisão)",
    tags: "ficcaocientifica suspense trabalho",
},
{
    titulo: "Wednesday",
    descricao: "Wednesday é uma série de comédia de terror que acompanha a personagem Wandinha Addams em sua jornada em uma nova escola. A série explora o lado mais sombrio e sarcástico da icônica família Addams.",
    link: "https://pt.wikipedia.org/wiki/Wednesday_(série_de_televisão)",
    tags: "addamsfamily terror comedia"
},
{
    titulo: "Succession",
    descricao: "Succession é um drama satírico que acompanha a família Roy, proprietária de um dos maiores conglomerados de mídia do mundo. A série explora as disputas pelo poder e as dinâmicas familiares complexas dentro dessa família bilionária.",
    link: "https://pt.wikipedia.org/wiki/Succession_(série_de_televisão)",
    tags: "drama familia poder dinheiro",
},
{
    titulo: "Severance",
    descricao: "Severance é uma série de ficção científica que explora o conceito de separação da vida profissional da pessoal. Os funcionários de uma empresa de tecnologia têm suas memórias do trabalho completamente separadas de suas vidas pessoais.",
    link: "https://pt.wikipedia.org/wiki/Severance_(série_de_televisão)",
    tags: "ficcaocientifica suspense trabalho",
},
{
    titulo: "Barry",
    descricao: "Barry é uma comédia negra que acompanha a vida dupla de Barry Berkman, um ex-marine que se torna um assassino de aluguel em Los Angeles e tenta se adaptar à vida como ator.",
    link: "https://pt.wikipedia.org/wiki/Barry_(série_de_televisão)",
    tags: "comedia negra assassinato ator"
},
{
    titulo: "Supernatural",
    descricao: "Supernatural é uma série de fantasia sombria que acompanha os irmãos Sam e Dean Winchester em suas viagens pelos Estados Unidos caçando criaturas sobrenaturais, como demônios, vampiros e fantasmas. A série explora temas como família, destino e a luta entre o bem e o mal.",
    link: "https://pt.wikipedia.org/wiki/Supernatural",
    tags: "fantasia sobrenatural irmãos winchester",
},
{
    titulo: "Peaky Blinders",
    descricao: "Peaky Blinders é uma série de drama histórico ambientada na Inglaterra da década de 1920. A trama se concentra na família Shelby, uma gangue de Birmingham que controla o crime organizado na cidade. A série explora temas como poder, família e a ascensão social.",
    link: "https://pt.wikipedia.org/wiki/Peaky_Blinders",
    tags: "historico gangue familia shelby",
},
{
    titulo: "Outer Banks",
    descricao: "Outer Banks é uma série de aventura adolescente ambientada nas ilhas barreira da Carolina do Norte. A trama gira em torno de um grupo de amigos que procuram um tesouro perdido e se envolvem em mistérios e perigos.",
    link: "https://pt.wikipedia.org/wiki/Outer_Banks",
    tags: "aventura adolescente tesouro ilha"
},
{
    titulo: "The Witcher",
    descricao: "The Witcher é uma série de fantasia épica baseada nos livros de Andrzej Sapkowski. A trama acompanha Geralt de Rivia, um caçador de monstros solitário, que se envolve em uma saga política e pessoal.",
    link: "https://pt.wikipedia.org/wiki/The_Witcher_(série_de_televisão)",
    tags: "fantasia geralt de rivia bruxo",
},
{
    titulo: "Sense8",
    descricao: "Sense8 é uma série de ficção científica que acompanha um grupo de pessoas de diferentes partes do mundo que são conectadas mentalmente. Eles descobrem que possuem habilidades especiais e precisam se unir para enfrentar uma ameaça global.",
    link: "https://pt.wikipedia.org/wiki/Sense8",
    tags: "ficcaocientifica conexões mentais global",
},
{
    titulo: "Westworld",
    descricao: "Westworld é uma série de ficção científica ambientada em um parque temático futurista povoado por androides. A trama explora temas como consciência, livre-arbítrio e a natureza da humanidade.",
    link: "https://pt.wikipedia.org/wiki/Westworld",
    tags: "ficcaocientifica androides parque tematico",
},
{
    titulo: "Lucifer",
    descricao: "Lucifer é uma série de drama com elementos sobrenaturais que acompanha o Lúcifer Morningstar, o diabo, que abandona o Inferno e se muda para Los Angeles, onde ele se torna um consultor da polícia.",
    link: "https://pt.wikipedia.org/wiki/Lucifer_(série_de_televisão)",
    tags: "sobrenatural diabo comedia",
},
{
    titulo: "Elite",
    descricao: "Elite é uma série de drama adolescente espanhol que se passa em um colégio interno de elite. A trama gira em torno das diferenças sociais e das consequências de um assassinato, explorando temas como amor, amizade e traição.",
    link: "https://pt.wikipedia.org/wiki/Elite_(série_de_televisão)",
    tags: "adolescente drama espanhol assassinato",
},
{
    titulo: "Jane the Virgin",
    descricao: "Jane the Virgin é uma comédia romântica americana que acompanha a vida de Jane Villanueva, uma jovem latina virgem e religiosa que descobre estar grávida após ser acidentalmente inseminada artificialmente.",
    link: "https://pt.wikipedia.org/wiki/Jane_the_Virgin",
    tags: "comedia romantica latina virgem",
},
{
    titulo: "Ginny & Georgia",
    descricao: "Ginny & Georgia é uma série de drama adolescente americana que acompanha Ginny Miller, uma adolescente que se muda com sua mãe, Georgia Miller, para uma nova cidade. A série explora temas como maternidade, amizade e os desafios da vida adolescente.",
    link: "https://pt.wikipedia.org/wiki/Ginny_and_Georgia",
    tags: "adolescente drama maternidade",
},
{
    titulo: "Schitt's Creek",
    descricao: "Schitt's Creek é uma comédia canadense que acompanha uma família rica que perde todo o seu dinheiro e é forçada a se mudar para uma pequena cidade que eles compraram como um presente de aniversário. A série é conhecida por seu humor inteligente e personagens cativantes.",
    link: "https://pt.wikipedia.org/wiki/Schitt's Creek",
    tags: "comedia familia pequena cidade",
},
{
    titulo: "Bridgerton",
    descricao: "Bridgerton é uma série de época dramática ambientada na Inglaterra do século XIX. A trama se concentra na alta sociedade londrina e nas vidas dos membros da família Bridgerton, explorando temas como amor, família e escândalos.",
    link: "https://pt.wikipedia.org/wiki/Bridgerton",
    tags: "epoca drama romance familia bridgerton",
},
{
    titulo: "Mr. Robot",
    descricao: "Mr. Robot é um thriller psicológico que acompanha Elliot Alderson, um programador com transtorno de ansiedade social que é recrutado por um misterioso grupo de hackers para derrubar uma das maiores corporações do mundo.",
    link: "https://pt.wikipedia.org/wiki/Mr_Robot",
    tags: "thriller hacker cibersegurança psicológico",
},
{
    titulo: "The Crown",
    descricao: "The Crown é uma série histórica dramática que retrata a vida da Rainha Elizabeth II e da família real britânica. A série explora os desafios e as responsabilidades da realeza, bem como os eventos históricos que moldaram o século XX.",
    link: "https://pt.wikipedia.org/wiki/The_Crown",
    tags: "historico drama rainha elizabeth ii familia real",
},
{
    titulo: "Sherlock",
    descricao: "Sherlock é uma série de drama policial britânica que reinventa o clássico detetive Sherlock Holmes, ambientada na Londres moderna. A série combina elementos de mistério, ação e humor, com um protagonista inteligente e excentrico.",
    link: "https://pt.wikipedia.org/wiki/Sherlock",
    tags: "policial mistério britânico detetive",
},
{
    titulo: "Killing Eve",
    descricao: "Killing Eve é um thriller psicológico que acompanha a caçada entre uma agente do MI6 e uma psicopata assassina. A série é conhecida por seus personagens complexos e sua dinâmica tensa e eletrizante.",
    link: "https://pt.wikipedia.org/wiki/Killing_Eve",
    tags: "thriller psicológico assassino agente mi6",
},
{
    titulo: "True Detective",
    descricao: "True Detective é uma antologia de drama policial que explora casos complexos e as vidas dos detetives que os investigam. Cada temporada apresenta uma história independente, com um elenco e uma atmosfera diferentes.",
    link: "https://pt.wikipedia.org/wiki/True_Detective",
    tags: "policial drama mistério antologia",
},
{
    titulo: "The Office (US)",
    descricao: "The Office (US) é uma comédia de situação mockumentary que satiriza a cultura corporativa americana. A série acompanha o dia a dia de um grupo de funcionários de uma empresa de papelaria, com um humor irônico e personagens memoráveis.",
    link: "https://pt.wikipedia.org/wiki/The_Office_(US)",
    tags: "comédia mockumentary escritório",
},
{
    titulo: "The Boys",
    descricao: "The Boys é uma série de super-heróis satírica que explora os lados sombrios dos super-heróis e as corporações que os controlam. A série é conhecida por sua violência gráfica e seu humor ácido.",
    link: "https://pt.wikipedia.org/wiki/The_Boys",
    tags: "super-herói sátira violência",
},
{
    titulo: "Dark",
    descricao: "Dark é uma série de ficção científica alemã que explora os temas de tempo, família e destino em uma pequena cidade alemã. A trama é complexa e envolvente, com múltiplas linhas do tempo e personagens interconectados.",
    link: "https://pt.wikipedia.org/wiki/Dark",
    tags: "ficção científica tempo viagem alemão mistério",
},
{
    titulo: "Ozark",
    descricao: "Ozark é um drama criminal que acompanha um contador financeiro que se muda com sua família para o Missouri rural, a fim de lavar dinheiro para um cartel mexicano. A série explora os temas de família, crime e as consequências de nossas escolhas.",
    link: "https://pt.wikipedia.org/wiki/Ozark",
    tags: "drama crime lavagem de dinheiro",
},
{
    titulo: "Eu, a Patroa e as Crianças",
    descricao: "Uma sitcom que acompanha o dia a dia de Michael Kyle, um pai de família afro-americano, e sua esposa Janet, enquanto tentam criar seus três filhos em um subúrbio. A série aborda temas como família, relacionamentos e a vida cotidiana de forma humorística.",
    link: "https://pt.wikipedia.org/wiki/My_Wife_and_Kids",
    tags: "sitcom familia afro-americana humor cotidiano",
},
{
    titulo: "Todo Mundo Odeia o Chris",
    descricao: "Baseada na vida do comediante Chris Rock, a série acompanha a infância de Chris em um bairro do Brooklyn nos anos 80. Com um humor sarcástico e observador, a série retrata as dificuldades e as alegrias de crescer em uma família afro-americana de classe média baixa.",
    link: "https://pt.wikipedia.org/wiki/Everybody_Hates_Chris",
    tags: "sitcom anos80 infância afro-americano humor sarcástico",
},
{
    titulo: "Um Maluco no Pedaço",
    descricao: "Will Smith estrela como um adolescente do oeste de Filadélfia que se muda para Bel-Air, um bairro rico de Los Angeles, para morar com seus tios ricos. A série é uma mistura de comédia, drama e música, abordando temas como racismo, classe social e família.",
    link: "https://pt.wikipedia.org/wiki/The_Fresh_Prince_of_Bel-Air",
    tags: "sitcom anos90 hip hop racismo classe social",
},
{
    titulo: "The Walking Dead",
    descricao: "Uma série de terror e drama que se passa em um mundo apocalíptico infestado de zumbis. A trama acompanha um grupo de sobreviventes enquanto eles lutam para se manter vivos e encontrar um lugar seguro.",
    link: "https://pt.wikipedia.org/wiki/The_Walking_Dead",
    tags: "terror drama zumbi apocalipse",
},
{
    titulo: "Grey's Anatomy",
    descricao: "Um drama médico que se passa em um hospital de Seattle. A série acompanha a vida pessoal e profissional de um grupo de médicos residentes, enquanto eles enfrentam desafios médicos e emocionais.",
    link: "https://pt.wikipedia.org/wiki/Grey%27s_Anatomy",
    tags: "drama médico hospital",
},
{
    titulo: "House",
    descricao: "Um drama médico que se passa em um hospital de Princeton. A série acompanha o Dr. Gregory House, um médico brilhante e antissocial que lidera uma equipe de diagnósticos médicos, enquanto ele resolve casos médicos complexos e enfrenta seus próprios demônios pessoais.",
    link: "https://pt.wikipedia.org/wiki/House_(série_de_televisão)",
    tags: "drama médico diagnóstico médico",
},
];
